FROM openjdk:21-jdk-slim

ARG DB_NAME
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_PORT
ARG DB_EXPOSE_PORT
ARG EXPOSE_PORT
ARG CONTAINER_PORT
ARG SECRET_KEY

ENV DB_NAME=${DB_NAME} \
    DB_USERNAME=${DB_USERNAME} \
    DB_PASSWORD=${DB_PASSWORD} \
    DB_PORT=${DB_PORT} \
    EXPOSE_PORT=${EXPOSE_PORT} \
    DB_EXPOSE_PORT=${DB_EXPOSE_PORT} \
    CONTAINER_PORT=${CONTAINER_PORT}\
    SECRET_KEY=${SECRET_KEY}

WORKDIR /app

COPY target/*.jar /app/ToDoListTesteTecnico.jar

EXPOSE ${EXPOSE_PORT}

ENTRYPOINT ["java", "-jar", "ToDoListTesteTecnico.jar"]