datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:${DB_EXPOSE_PORT}/${DB_NAME}?useTimezone=true&serverTimezone=UTC
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
